"""add soft delete to scripts table

Revision ID: 1234567abcde
Revises: a0b1ffd03659
Create Date: 2025-03-26 09:43:12.368659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1234567abcde'
down_revision: Union[str, None] = '01234567abcd'  # This should refer to the previous migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add soft delete columns to the scripts table
    op.add_column('scripts', sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='False'))
    op.add_column('scripts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove soft delete columns from the scripts table
    op.drop_column('scripts', 'deleted_at')
    op.drop_column('scripts', 'is_deleted')
    
    # ### end Alembic commands ###