"""recreate_beats_table

Revision ID: 1b35381aa0e2
Revises: 2035ec976c9c
Create Date: 2025-02-20 03:02:17.915723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b35381aa0e2'
down_revision: Union[str, None] = '2035ec976c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beats',
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('master_beat_sheet_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('beat_title', sa.String(length=255), nullable=False),
    sa.Column('beat_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('beat_act', sa.Enum('act_1', 'act_2a', 'act_2b', 'act_3', name='actenum'), nullable=False),
    sa.Column('complete_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['master_beat_sheet_id'], ['master_beat_sheets.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_id', 'beat_title', name='unique_beat_title_per_script'),
    sa.UniqueConstraint('script_id', 'position', name='unique_position_per_script')
    )
    op.create_index(op.f('ix_beats_id'), 'beats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beats_id'), table_name='beats')
    op.drop_table('beats')
    # ### end Alembic commands ###
