"""adding script progress to script table

Revision ID: 1b7252df88d6
Revises: eef5f3c2a891
Create Date: 2025-02-18 02:25:10.363503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7252df88d6'
down_revision: Union[str, None] = 'eef5f3c2a891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('script_progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'script_progress')
    # ### end Alembic commands ###
