"""scenes table added

Revision ID: 1ef30e8cdf00
Revises: 1b35381aa0e2
Create Date: 2025-02-21 01:24:56.561745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef30e8cdf00'
down_revision: Union[str, None] = '1b35381aa0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('beats', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # op.add_column('scene_generation_tracker', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # op.add_column('scene_generation_tracker', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # op.add_column('scenes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # op.add_column('scenes', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # op.alter_column('scenes', 'position',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Float(),
    #            existing_nullable=False)
    # op.alter_column('scenes', 'scene_heading',
    #            existing_type=sa.VARCHAR(length=255),
    #            type_=sa.String(length=1000),
    #            existing_nullable=False)
    # op.drop_constraint('unique_position_per_beat', 'scenes', type_='unique')
    # op.create_unique_constraint('unique_position_per_beat', 'scenes', ['beat_id', 'position', 'is_deleted'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_position_per_beat', 'scenes', type_='unique')
    # op.create_unique_constraint('unique_position_per_beat', 'scenes', ['beat_id', 'position'])
    # op.alter_column('scenes', 'scene_heading',
    #            existing_type=sa.String(length=1000),
    #            type_=sa.VARCHAR(length=255),
    #            existing_nullable=False)
    # op.alter_column('scenes', 'position',
    #            existing_type=sa.Float(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=False)
    # op.drop_column('scenes', 'is_deleted')
    # op.drop_column('scenes', 'deleted_at')
    # op.drop_column('scene_generation_tracker', 'is_deleted')
    # op.drop_column('scene_generation_tracker', 'deleted_at')
    op.drop_column('beats', 'is_deleted')
    op.drop_column('beats', 'deleted_at')
    # ### end Alembic commands ###
