"""add shortening alternatives table

Revision ID: 23456789abcd
Revises: 1234567abcde
Create Date: 2025-04-02 16:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23456789abcd'
down_revision: Union[str, None] = '1234567abcde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the ShorteningAlternativeType enum
    # shortening_alternative_type = sa.Enum(
    #     'concise', 'dramatic', 'minimal', 'poetic', 'punchy',
    #     name='shorteningalternativetype'
    # )
    # shortening_alternative_type.create(op.get_bind(), checkfirst=True)
    
    # Create the shortening_alternatives table
    op.create_table(
        'shortening_alternatives',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('component_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('alternative_type', sa.Text(), nullable=True),
        sa.Column('shortened_text', sa.Text(), nullable=False),
        sa.Column('explanation', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['component_id'], ['scene_segment_components.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('component_id', 'alternative_type', name='unique_alternative_type_per_component')
    )
    
    # Add index on id column
    op.create_index(op.f('ix_shortening_alternatives_id'), 'shortening_alternatives', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the index
    op.drop_index(op.f('ix_shortening_alternatives_id'), table_name='shortening_alternatives')
    
    # Drop the table
    op.drop_table('shortening_alternatives')
    
    # Drop the enum type
    sa.Enum(name='shorteningalternativetype').drop(op.get_bind(), checkfirst=True)
    
    # ### end Alembic commands ###