"""restoring scenes table

Revision ID: 30557548312e
Revises: 7a7a739858e9
Create Date: 2025-02-22 20:32:53.903985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30557548312e'
down_revision: Union[str, None] = '7a7a739858e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('scene-descriptions',
    # sa.Column('beat_id', sa.UUID(), nullable=False),
    # sa.Column('position', sa.Float(), nullable=False),
    # sa.Column('scene_heading', sa.String(length=1000), nullable=False),
    # sa.Column('scene_description', sa.Text(), nullable=False),
    # sa.Column('dialogue_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    # sa.Column('estimated_duration', sa.Float(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('is_deleted', sa.Boolean(), nullable=True),
    # sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id'),
    # )
    # op.create_index(op.f('ix_scenes_id'), 'scenes', ['id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.drop_index(op.f('ix_scenes_id'), table_name='scenes')
    # op.drop_table('scenes')
    # ### end Alembic commands ###
