"""add shortening selection history table

Revision ID: 34567890abce
Revises: 23456789abcd
Create Date: 2025-04-02 17:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34567890abce'
down_revision: Union[str, None] = '23456789abcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the shortening_selection_history table
    op.create_table(
        'shortening_selection_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('component_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('alternative_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('alternative_type', sa.Text(), nullable=True),
        sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['alternative_id'], ['shortening_alternatives.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['component_id'], ['scene_segment_components.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Add index on id column
    op.create_index(op.f('ix_shortening_selection_history_id'), 'shortening_selection_history', ['id'], unique=False)
    
    # Add index on the selection timestamp for easier querying by date range
    op.create_index(op.f('ix_shortening_selection_history_selected_at'), 'shortening_selection_history', ['selected_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the indexes
    op.drop_index(op.f('ix_shortening_selection_history_selected_at'), table_name='shortening_selection_history')
    op.drop_index(op.f('ix_shortening_selection_history_id'), table_name='shortening_selection_history')
    
    # Drop the table
    op.drop_table('shortening_selection_history')
    
    # ### end Alembic commands ###