"""adding beats to sql model - update

Revision ID: 3541aa926db2
Revises: 6ed6bb0e8628
Create Date: 2025-02-20 01:50:16.014889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3541aa926db2'
down_revision: Union[str, None] = '6ed6bb0e8628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_beat_sheets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beat_sheet_type', sa.Enum('BLAKE_SNYDER', 'HERO_JOURNEY', 'STORY_CIRCLE', 'PIXAR_STRUCTURE', 'TV_BEAT_SHEET', 'MINI_MOVIE', 'INDIE_FILM', name='beatsheettype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('number_of_beats', sa.Integer(), nullable=False),
    sa.Column('template', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beat_sheet_type')
    )
    op.create_index(op.f('ix_master_beat_sheets_id'), 'master_beat_sheets', ['id'], unique=False)
    op.create_table('beats',
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('master_beat_sheet_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('beat_title', sa.String(length=255), nullable=False),
    sa.Column('beat_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complete_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['master_beat_sheet_id'], ['master_beat_sheets.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_id', 'beat_title', name='unique_beat_title_per_script'),
    sa.UniqueConstraint('script_id', 'position', name='unique_position_per_script')
    )
    op.create_index(op.f('ix_beats_id'), 'beats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beats_id'), table_name='beats')
    op.drop_table('beats')
    op.drop_index(op.f('ix_master_beat_sheets_id'), table_name='master_beat_sheets')
    op.drop_table('master_beat_sheets')
    # ### end Alembic commands ###
