"""add rewrite alternatives tables

Revision ID: 45678901abcd
Revises: 34567890abce
Create Date: 2025-04-03 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45678901abcd'
down_revision: Union[str, None] = '34567890abce'  # This should refer to the previous migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the rewrite_alternatives table
    op.create_table(
        'rewrite_alternatives',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('component_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('alternative_type', sa.Text(), nullable=True),
        sa.Column('rewritten_text', sa.Text(), nullable=False),
        sa.Column('explanation', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['component_id'], ['scene_segment_components.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('component_id', 'alternative_type', name='unique_rewrite_alternative_type_per_component')
    )
    
    # Add index on id column
    op.create_index(op.f('ix_rewrite_alternatives_id'), 'rewrite_alternatives', ['id'], unique=False)
    
    # Create the rewrite_selection_history table
    op.create_table(
        'rewrite_selection_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('component_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('alternative_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('alternative_type', sa.Text(), nullable=False),
        sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['alternative_id'], ['rewrite_alternatives.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['component_id'], ['scene_segment_components.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Add indexes
    op.create_index(op.f('ix_rewrite_selection_history_id'), 'rewrite_selection_history', ['id'], unique=False)
    op.create_index(op.f('ix_rewrite_selection_history_selected_at'), 'rewrite_selection_history', ['selected_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index(op.f('ix_rewrite_selection_history_selected_at'), table_name='rewrite_selection_history')
    op.drop_index(op.f('ix_rewrite_selection_history_id'), table_name='rewrite_selection_history')
    
    # Drop tables
    op.drop_table('rewrite_selection_history')
    op.drop_index(op.f('ix_rewrite_alternatives_id'), table_name='rewrite_alternatives')
    op.drop_table('rewrite_alternatives')
    
    # ### end Alembic commands ###