"""adding scene description

Revision ID: 587b43339ba0
Revises: b09796dfc89d
Create Date: 2025-02-23 01:41:07.211217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587b43339ba0'
down_revision: Union[str, None] = 'b09796dfc89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene-description',
    sa.Column('beat_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('scene_heading', sa.String(length=1000), nullable=False),
    sa.Column('scene_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('beat_id', 'position', name='unique_position_per_beat')
    )
    op.create_index(op.f('ix_scene-description_id'), 'scene-description', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene-description_id'), table_name='scene-description')
    op.drop_table('scene-description')
    # ### end Alembic commands ###
