"""adding supabase uid to user table

Revision ID: 5c8405a948d1
Revises: ee7535f29148
Create Date: 2025-02-18 01:51:14.308905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8405a948d1'
down_revision: Union[str, None] = 'ee7535f29148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supabase_uid', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'supabase_uid')
    # ### end Alembic commands ###
