"""add continuation alternatives tables

Revision ID: 67890123abcd
Revises: 56789012abcd
Create Date: 2025-04-11 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67890123abcd'
down_revision: Union[str, None] = '56789012abcd'  # Make sure this points to your previous migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the continuation_alternatives table
    op.create_table(
        'continuation_alternatives',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('component_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('alternative_type', sa.Text(), nullable=True),
        sa.Column('continuation_text', sa.Text(), nullable=False),
        sa.Column('explanation', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['component_id'], ['scene_segment_components.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('component_id', 'alternative_type', name='unique_continuation_alternative_type_per_component')
    )
    
    # Add index on id column
    op.create_index(op.f('ix_continuation_alternatives_id'), 'continuation_alternatives', ['id'], unique=False)
    
    # Create the continuation_selection_history table
    op.create_table(
        'continuation_selection_history',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('component_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('alternative_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('alternative_type', sa.Text(), nullable=False),
        sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['alternative_id'], ['continuation_alternatives.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['component_id'], ['scene_segment_components.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Add index on id column
    op.create_index(op.f('ix_continuation_selection_history_id'), 'continuation_selection_history', ['id'], unique=False)
    
    # Add index on the selection timestamp for easier querying by date range
    op.create_index(op.f('ix_continuation_selection_history_selected_at'), 'continuation_selection_history', ['selected_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the indexes
    op.drop_index(op.f('ix_continuation_selection_history_selected_at'), table_name='continuation_selection_history')
    op.drop_index(op.f('ix_continuation_selection_history_id'), table_name='continuation_selection_history')
    
    # Drop the tables
    op.drop_table('continuation_selection_history')
    op.drop_index(op.f('ix_continuation_alternatives_id'), table_name='continuation_alternatives')
    op.drop_table('continuation_alternatives')
    
    # ### end Alembic commands ###