"""adding beats to sql model

Revision ID: 6ed6bb0e8628
Revises: c73a4ce38d14
Create Date: 2025-02-20 01:46:02.566949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed6bb0e8628'
down_revision: Union[str, None] = 'c73a4ce38d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
