"""correct scene descriptionss

Revision ID: 8f4bfe0ac15b
Revises: fc7b458d565f
Create Date: 2025-02-23 03:26:35.276496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4bfe0ac15b'
down_revision: Union[str, None] = 'fc7b458d565f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
