"""adding beat act to beats column

Revision ID: 9996f32986ae
Revises: 3541aa926db2
Create Date: 2025-02-20 02:21:44.877049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9996f32986ae'
down_revision: Union[str, None] = '3541aa926db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('beat_act', sa.Enum('act_1', 'act_2', 'act_3', name='actenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beats', 'beat_act')
    # ### end Alembic commands ###
