"""adding character to scene segment enums

Revision ID: a0b1ffd03659
Revises: ee91ea496743
Create Date: 2025-03-04 02:32:08.368659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'a0b1ffd03659'
down_revision: Union[str, None] = 'ee91ea496743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


old_enum = ENUM("HEADING", "ACTION", "DIALOGUE", "TRANSITION", name="componenttype", create_type=False)
new_enum = ENUM("HEADING", "ACTION", "DIALOGUE", "TRANSITION", "CHARACTER", name="componenttype", create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE componenttype ADD VALUE 'CHARACTER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE your_table_name ALTER COLUMN component_type TYPE VARCHAR")
    old_enum.drop(op.get_bind(), checkfirst=True)
    old_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE your_table_name ALTER COLUMN component_type TYPE componenttype USING component_type::componenttype")
