"""add script creation method and progress tracking

Revision ID: c73a4ce38d14
Revises: 1b7252df88d6
Create Date: 2025-02-18 22:52:34.299838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73a4ce38d14'
down_revision: Union[str, None] = '1b7252df88d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('creation_method', sa.Enum('FROM_SCRATCH', 'WITH_AI', 'UPLOAD', name='scriptcreationmethod'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'creation_method')
    # ### end Alembic commands ###
