"""adding superuser boolean to user table

Revision ID: eef5f3c2a891
Revises: 5c8405a948d1
Create Date: 2025-02-18 02:11:10.988179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef5f3c2a891'
down_revision: Union[str, None] = '5c8405a948d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_user')
    # ### end Alembic commands ###
