"""correct scene description

Revision ID: fc7b458d565f
Revises: 2b57188b345f
Create Date: 2025-02-23 02:30:42.191482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc7b458d565f'
down_revision: Union[str, None] = '2b57188b345f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_description_beats',
    sa.Column('beat_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('scene_heading', sa.String(length=1000), nullable=False),
    sa.Column('scene_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_description_beats_id'), 'scene_description_beats', ['id'], unique=False)
    op.drop_index('ix_scene-description-beats_id', table_name='scene-description-beats')
    op.drop_table('scene-description-beats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene-description-beats',
    sa.Column('beat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scene_heading', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('scene_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], name='scene-description-beats_beat_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='scene-description-beats_pkey')
    )
    op.create_index('ix_scene-description-beats_id', 'scene-description-beats', ['id'], unique=False)
    op.drop_index(op.f('ix_scene_description_beats_id'), table_name='scene_description_beats')
    op.drop_table('scene_description_beats')
    # ### end Alembic commands ###
